In [2]:
import numpy as np

In [3]:
array_1d = np.array([1,2,3,4])
print(array_1d,array_1d.shape)

[1 2 3 4] (4,)


In [6]:
array_2d= np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(array_2d,array_2d.shape)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]] (3, 4)


In [10]:
array_3d= np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                    [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                    [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                    [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                    [[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(array_3d,array_3d.shape)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]] (5, 3, 4)


In [18]:
# O reshape serve para indicar quantas linhas e colunas deve existir no array
a=np.array(range(21)).reshape(7,3)
print(a,a.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]] (7, 3)


In [19]:
a=np.array(range(27)).reshape(3,3,3)
print(a,a.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] (3, 3, 3)


In [23]:
#Printando elementos do array.
print(a[1,2,1]) #Acessando a segunda matriz (indice 0), terceira linha e segunda coluna.
print(a[2,2,1])
print(a[0,2,2])

16
25
8


In [35]:
# print(a,'\n','-'*13)
print(a[0:2],'\n','-'*13) #Dando um slice para pegar somente até a segunda matriz (indice 1).
print(a[0:2,1:2],'\n','-'*13) #Pegando as 2 primeiras matrizes e somente a segunda linha de cada.
print(a[0:2,0:1,0:1]) #Pegando as 2 primeiras matrizes, somente a primeira linha 
# e somente a primeira coluna.

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] 
 -------------
[[[ 3  4  5]]

 [[12 13 14]]] 
 -------------
[[[0]]

 [[9]]]


In [37]:
for x in a:
    print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [38]:
for x in a:
    for y in x:
        print(y)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]
[24 25 26]


In [39]:
for x in a:
    for y in x:
        for z in y:
            print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
